Standardise the format of the bash files

diff --git a/git/commit-msg-hook b/git/commit-msg-hook
--- a/git/commit-msg-hook
+++ b/git/commit-msg-hook
@@ -5,15 +5,15 @@ set -euo pipefail
 MSG="$1"
 
 check_for_duplicate() {
-    test "" = "$(grep "^$2: " "$1" |
-        sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
-        cat "$1" >&2
-        echo >&2
-        echo "Your commit cannot have the same name duplicated in the $2 field" >&2
-        
-        exit 1
-    }
+	test "" = "$(grep "^$2: " "$1" |
+		sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
+		cat "$1" >&2
+		echo >&2
+		echo "Your commit cannot have the same name duplicated in the $2 field" >&2
+
+		exit 1
+	}
 }
 
-check_for_duplicate "$MSG" Signed-off-by 
+check_for_duplicate "$MSG" Signed-off-by
 check_for_duplicate "$MSG" Co-authored-by
diff --git a/git/commit-msg-hook-work b/git/commit-msg-hook-work
--- a/git/commit-msg-hook-work
+++ b/git/commit-msg-hook-work
@@ -5,20 +5,21 @@ set -euo pipefail
 MSG="$1"
 
 check_for_duplicate() {
-    test "" = "$(grep "^$2: " "$1" |
-        sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
-        cat "$1" >&2
-        echo >&2
-        echo "Your commit cannot have the same name duplicated in the $2 field" >&2
-        
-        exit 1
-    }
+	test "" = "$(grep "^$2: " "$1" |
+		sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
+		cat "$1" >&2
+		echo >&2
+		echo "Your commit cannot have the same name duplicated in the $2 field" >&2
+
+		exit 1
+	}
 }
 
 check_for_tracker_id() {
-    if ! grep -qE '\[(([Dd]elivers|[Ff]ixes|[Ff]inishes) #[0-9]+|(#[0-9]+))([ ,]#[0-9]+)?\]' "$1";then
-        cat "$1" >&2
-        ( 1>&2 cat << EOF
+	if ! grep -qE '\[(([Dd]elivers|[Ff]ixes|[Ff]inishes) #[0-9]+|(#[0-9]+))([ ,]#[0-9]+)?\]' "$1"; then
+		cat "$1" >&2
+		(
+			cat 1>&2 <<EOF
     Your commit message must contain the a pivotal tracker story id in the format [#4576346] somewhere in the message"
     Examples:
     [Delivers #12345678]
@@ -29,12 +30,12 @@ check_for_tracker_id() {
     [#12345678],[#12345884]
     This will address [#12345884]
 EOF
-        )
+		)
 
-        exit 1
-    fi
+		exit 1
+	fi
 }
 
-check_for_duplicate "$MSG" Signed-off-by 
+check_for_duplicate "$MSG" Signed-off-by
 check_for_duplicate "$MSG" Co-authored-by
 check_for_tracker_id "$MSG"
