Add something

diff --git a/1password/bin/1password b/1password/bin/1password
--- a/1password/bin/1password
+++ b/1password/bin/1password
@@ -26,23 +26,27 @@ function run_op() {
 
 # Check token still valid
 if [ -f "$CACHE_FILE" ]; then
-  ERROR=$(run_op list vaults 2>&1 >/dev/null)
+  ERROR=$(run_op list vaults 2>&1 >/dev/null || true)
 
   if [[ $ERROR == *"session expired, sign in to create a new session"* ]]; then
+    echo "$ERROR" >/dev/stderr
     rm "$CACHE_FILE"
   fi
 
   if [[ $ERROR == *"Session token is empty"* ]]; then
+    echo "$ERROR" >/dev/stderr
     rm "$CACHE_FILE"
   fi
 
   if [[ $ERROR == *"You are not currently signed in."* ]]; then
+    echo "$ERROR" >/dev/stderr
     rm "$CACHE_FILE"
   fi
 fi
 
 # Login
 if ! [ -f "$CACHE_FILE" ]; then
+  echo "No current session, logging you in"
   op signin --raw | sops --encrypt /dev/stdin >"$CACHE_FILE"
 fi
 
